#!/usr/bin/env bash

set -e

zone_name=$1
hosted_zone_id=$(
  aws route53 list-hosted-zones --output text \
    --query "HostedZones[?Name == '$zone_name.'].Id | [0]"
)

aws route53 list-resource-record-sets --hosted-zone-id "$hosted_zone_id" --output json \
  | jq -jr '.ResourceRecordSets[] | "\(.Name) \t\(.TTL) \t\(.Type) \t\(.ResourceRecords[]?.Value)\n"'
