#!/usr/bin/env bash

options=$(getopt -o g:: --long git-add:: -- "$@") || exit
eval set -- "$options"

while true; do
  case "$1" in
  -g | --git-add)
    repo_path=$(git rev-parse --show-toplevel) || exit
    shift 2
    ;;
  --)
    shift
    break
    ;;
  *)
    echo "Internal error!"
    exit 1
    ;;
  esac
done

function_path=${1:?"function name is required"}
function_name="$(basename $function_path)"

add_if_in_repo() {
  local file_name="$1"

  if [ "$repo_path" ]; then
    git add "$file_name"
  fi
}

cat << TS_FUNCTION_SPEC > "$function_path.spec.ts"
describe('$function_name', () => {
  //
});
TS_FUNCTION_SPEC

add_if_in_repo "$function_path.spec.ts"
