#!/usr/bin/env bash

options=$(getopt -o g:: --long git-add:: -- "$@") || exit
eval set -- "$options"

while true; do
  case "$1" in
  -g | --git-add)
    repo_path=$(git rev-parse --show-toplevel) || exit
    shift 2
    ;;
  --)
    shift
    break
    ;;
  *)
    echo "Internal error!"
    exit 1
    ;;
  esac
done

function_full=${1:?"function name is required"}
function_path="$(dirname "$function_full")"
function_name="$(basename "$function_full")"

add_if_in_repo() {
  local file_name="$1"

  if [ "$repo_path" ]; then
    git add "$file_name"
  fi
}

mkdir -p "$function_path"

cat << TS_FUNCTION_SPEC > "$function_full.spec.ts"
describe('$function_name', () => {
  //
});
TS_FUNCTION_SPEC

add_if_in_repo "$function_full.spec.ts"
