#!/usr/bin/env bash
set +e

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # iterate until no longer a symlink
  DIR="$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)"
  SOURCE="$(readlink "$SOURCE")"

  # check if relative symlink
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)"

scripts=(
  "cd_to_project"
  "git_commit_file_as_executable"
  "link_scripts_to_local_bin"
  "npm_audit_fix_and_push"
  "npm_update_package_and_commit"
)

for script in "${scripts[@]}"; do
  chmod +x "$DIR/$script"
  ln -sf "$DIR/$script" /usr/local/bin/
done
