#!/usr/bin/env bash
set +e

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # iterate until no longer a symlink
  DIR="$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)"
  SOURCE="$(readlink "$SOURCE")"

  # check if relative symlink
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$(cd -P "$(dirname "$SOURCE")" >/dev/null 2>&1 && pwd)"

scripts=(
  "mknano"
  "mktouch"
  "cd_to_project"
  "git_add_file_as_executable"
  "git_rename_and_commit"
  "git_compare_branches"
  "gen_ts_barrel"
  "gen_ts_function_spec"
  "aws_get_ami_of_latest_ecs_optimized_linux"
  "link_scripts_to_local_bin"
  "npm_audit_fix_and_push"
  "npm_update_package_and_commit"
  "npm_update_package_and_commit_multiple"
)

for script in "${scripts[@]}"; do
  chmod +x "$DIR/$script"
  echo "linking $script"
  ln -sf "$DIR/$script" /usr/local/bin/
done
