#!/usr/bin/env bash

git_branch=${1:-master}

if [ ! -f "$PWD/package-lock.json" ]; then echo "cannot run npm here!" && exit; fi
git status # output the status, stopping if it failed
if [ "$?" -ne 0 ]; then exit 1; fi

if [ "$(git status -suno | wc -l)" -ne 0 ]; then echo "working directory isn't clean!" && exit; fi

branch_name="security-updates-$(date +%s)"

git checkout "$git_branch"
git fetch --all
git pull
git checkout -b "$branch_name"
npm audit fix --package-lock-only
git commit package.json package-lock.json -m 'Run `npm audit fix`'
git push --set-upstream origin "$branch_name"
echo 'done'
